language: java
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
before_install:
  - chmod +x gradlew
before_script:
  - gradle clean assemble
scripts:
  - gradle check
  - gradle test
branches:
  only:
    - master
